"""
VAPID Key Generator

Generate P-256 curve VAPID keys for Web Push notifications.
Run this script once to generate your keys, then copy them to .env

Usage:
    python generate_vapid_keys.py
"""

import os
import base64
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend


def urlsafe_base64_encode(data: bytes) -> str:
    """Encode bytes to URL-safe Base64 string (no padding)"""
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode('ascii')


def generate_vapid_keys():
    """Generate a new VAPID key pair using P-256 curve"""
    
    # Generate private key using P-256 curve (required by Web Push spec)
    private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
    
    # Get public key
    public_key = private_key.public_key()
    
    # Serialize private key to raw bytes (32 bytes for P-256)
    private_bytes = private_key.private_numbers().private_value.to_bytes(32, byteorder='big')
    
    # Serialize public key: 0x04 prefix + x coordinate (32 bytes) + y coordinate (32 bytes)
    public_numbers = public_key.public_numbers()
    x_bytes = public_numbers.x.to_bytes(32, byteorder='big')
    y_bytes = public_numbers.y.to_bytes(32, byteorder='big')
    public_bytes = b'\x04' + x_bytes + y_bytes
    
    # Convert to URL-safe Base64
    vapid_private_key = urlsafe_base64_encode(private_bytes)
    vapid_public_key = urlsafe_base64_encode(public_bytes)
    
    return vapid_private_key, vapid_public_key


def main():
    print("=" * 60)
    print("VAPID Key Generator for Web Push Notifications")
    print("=" * 60)
    print()
    
    private_key, public_key = generate_vapid_keys()
    
    print("Generated VAPID Keys:")
    print("-" * 60)
    print(f"VAPID_PRIVATE_KEY={private_key}")
    print(f"VAPID_PUBLIC_KEY={public_key}")
    print("-" * 60)
    print()
    
    print("Instructions:")
    print("1. Copy the above keys to your .env file")
    print("2. Update VAPID_CONTACT with your email address")
    print("3. Restart your backend server")
    print()
    
    # Create .env.example file
    env_example_content = f"""# Web Push Notification Backend Configuration
# Generated by generate_vapid_keys.py

# VAPID Keys (P-256 curve)
# Generate new keys with: python generate_vapid_keys.py
VAPID_PRIVATE_KEY={private_key}
VAPID_PUBLIC_KEY={public_key}

# Contact email for VAPID (required by specification)
# Use a real email where browser vendors can reach you if needed
VAPID_CONTACT=admin@example.com

# Frontend URL for CORS configuration
# Update this to your Vercel production URL
FRONTEND_URL=http://localhost:3000

# Server configuration
PORT=8000

# Database path (SQLite)
DATABASE_PATH=subscriptions.db
"""
    
    env_path = os.path.join(os.path.dirname(__file__), '.env.example')
    with open(env_path, 'w') as f:
        f.write(env_example_content)
    
    print(f"✅ Created .env.example at: {env_path}")
    print()
    print("Security Note:")
    print("- Keep VAPID_PRIVATE_KEY secret - never commit it to version control")
    print("- VAPID_PUBLIC_KEY can be shared publicly (used by frontend)")
    print("- Add .env to your .gitignore file")
    print()


if __name__ == "__main__":
    main()
